# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-03-23 12:59
from __future__ import unicode_literals

import autoslug.fields
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=75, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('description', models.CharField(blank=True, max_length=255, verbose_name='description')),
                ('color', models.CharField(blank=True, help_text='Title color in hex format (i.e: #1aafd0).', max_length=7, verbose_name='color')),
                ('is_global', models.BooleanField(default=True, help_text='Designates whether the topics will bedisplayed in the all-categories list.', verbose_name='global')),
                ('is_closed', models.BooleanField(default=False, verbose_name='closed')),
                ('is_removed', models.BooleanField(default=False, verbose_name='removed')),
                ('is_private', models.BooleanField(default=False, verbose_name='private')),
                ('parent', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_spirit.Category', verbose_name='category parent')),
            ],
            options={
                'ordering': ['-pk'],
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='title')),
                ('slug', autoslug.fields.AutoSlugField(blank=True, editable=False, populate_from='title')),
                ('date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date')),
                ('last_active', models.DateTimeField(default=django.utils.timezone.now, verbose_name='last active')),
                ('is_pinned', models.BooleanField(default=False, verbose_name='pinned')),
                ('is_globally_pinned', models.BooleanField(default=False, verbose_name='globally pinned')),
                ('is_closed', models.BooleanField(default=False, verbose_name='closed')),
                ('is_removed', models.BooleanField(default=False)),
                ('view_count', models.PositiveIntegerField(default=0, verbose_name='views count')),
                ('comment_count', models.PositiveIntegerField(default=0, verbose_name='comment count')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drf_spirit.Category', verbose_name='category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='spirit_topics', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-last_active', '-pk'],
                'verbose_name': 'topic',
                'verbose_name_plural': 'topics',
            },
        ),
    ]
