# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 13:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0002_auto_20170324_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drf_spirit.Category', verbose_name='category parent'),
        ),
    ]
