# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-06 13:44
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('drf_spirit', '0003_auto_20170324_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='ip_address',
            field=models.GenericIPAddressField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='comment',
            name='is_modified',
            field=models.BooleanField(default=False, editable=False),
        ),
        migrations.AlterField(
            model_name='comment',
            name='likes_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='likes count'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='modified_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='modified count'),
        ),
        migrations.AlterField(
            model_name='comment',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='forum_comments', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='comment_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='comment count'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_globally_pinned',
            field=models.BooleanField(default=False, editable=False, verbose_name='globally pinned'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='is_pinned',
            field=models.BooleanField(default=False, editable=False, verbose_name='pinned'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='last_active',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, editable=False, verbose_name='last active'),
        ),
        migrations.AlterField(
            model_name='topic',
            name='user',
            field=models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='spirit_topics', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='topic',
            name='view_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='views count'),
        ),
    ]
